# Generated by Django 2.2.5 on 2019-09-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(db_column='idArea', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('idatributo', models.AutoField(db_column='idAtributo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'atributo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('idauditoria', models.AutoField(db_column='idAuditoria', primary_key=True, serialize=False)),
                ('id_registro_afectado', models.IntegerField(blank=True, db_column='Id_Registro_Afectado', null=True)),
                ('tabla_afectada', models.CharField(blank=True, db_column='Tabla_Afectada', max_length=45, null=True)),
                ('accion', models.CharField(blank=True, db_column='Accion', max_length=45, null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('ip', models.CharField(blank=True, db_column='Ip', max_length=18, null=True)),
                ('usuario_ad_idusuario_ad', models.IntegerField(db_column='Usuario_AD_idUsuario_AD')),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.AutoField(db_column='idCargo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', models.AutoField(db_column='idCuenta', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=45, null=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=45, null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.AutoField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(db_column='idEmpresa', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.AutoField(db_column='idEquipo', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=45, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=45, null=True)),
                ('nro_serie', models.CharField(blank=True, db_column='Nro_Serie', max_length=45, null=True)),
                ('nro_activo_fijo', models.CharField(blank=True, db_column='Nro_Activo_Fijo', max_length=45, null=True)),
                ('ip', models.CharField(blank=True, db_column='Ip', max_length=18, null=True)),
                ('ultima_observacion', models.CharField(blank=True, db_column='Ultima_Observacion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('idgerencia', models.AutoField(db_column='idGerencia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'gerencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('idlicencia', models.AutoField(db_column='idLicencia', primary_key=True, serialize=False)),
                ('producto', models.CharField(blank=True, db_column='Producto', max_length=45, null=True)),
                ('llave_activacion', models.CharField(blank=True, db_column='Llave_Activacion', max_length=45, null=True)),
                ('version', models.CharField(blank=True, db_column='Version', max_length=10, null=True)),
            ],
            options={
                'db_table': 'licencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('idos', models.AutoField(db_column='idOS', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=25, null=True)),
                ('servicio', models.CharField(blank=True, db_column='Servicio', max_length=20, null=True)),
                ('arquitectura', models.CharField(blank=True, db_column='Arquitectura', max_length=5, null=True)),
            ],
            options={
                'db_table': 'os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idpermiso', models.AutoField(db_column='idPermiso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('idregional', models.AutoField(db_column='idRegional', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'regional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idubicacion', models.AutoField(db_column='idUbicacion', primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=45, null=True)),
                ('edificio', models.CharField(blank=True, db_column='Edificio', max_length=45, null=True)),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioAd',
            fields=[
                ('idusuario_ad', models.AutoField(db_column='idUsuario_AD', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=15, null=True)),
            ],
            options={
                'db_table': 'usuario_ad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCorreo',
            fields=[
                ('idusuario_correo', models.AutoField(db_column='idUsuario_Correo', primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=45, null=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=45, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'usuario_correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoHasAtributo',
            fields=[
                ('equipo_idequipo', models.ForeignKey(db_column='Equipo_idEquipo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sofia_App.Equipo')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'equipo_has_atributo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('idimpresora', models.ForeignKey(db_column='idImpresora', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sofia_App.Equipo')),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=45, null=True)),
                ('tinta', models.CharField(blank=True, db_column='Tinta', max_length=45, null=True)),
            ],
            options={
                'db_table': 'impresora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenador',
            fields=[
                ('idordenador', models.ForeignKey(db_column='idOrdenador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sofia_App.Equipo')),
                ('mac', models.CharField(blank=True, db_column='MAC', max_length=25, null=True)),
                ('hostname', models.CharField(blank=True, db_column='HostName', max_length=25, null=True)),
                ('procesador', models.CharField(blank=True, db_column='Procesador', max_length=45, null=True)),
                ('ram', models.CharField(blank=True, db_column='RAM', max_length=10, null=True)),
                ('almacenamiento', models.CharField(blank=True, db_column='Almacenamiento', max_length=10, null=True)),
                ('tipo_almacenamiento', models.CharField(blank=True, db_column='Tipo_Almacenamiento', max_length=10, null=True)),
            ],
            options={
                'db_table': 'ordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsHasOrdenador',
            fields=[
                ('os_idos', models.ForeignKey(db_column='OS_idOS', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sofia_App.Os')),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='Fecha_Inicio', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='Fecha_Fin', null=True)),
            ],
            options={
                'db_table': 'os_has_ordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtroDispositivo',
            fields=[
                ('idotro_dispositivo', models.ForeignKey(db_column='idOtro_Dispositivo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sofia_App.Equipo')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
            ],
            options={
                'db_table': 'otro_dispositivo',
                'managed': False,
            },
        ),
    ]
